"""add author surname

Revision ID: 9ff5948f8b71
Revises: 69de1805334b
Create Date: 2022-12-23 17:30:34.447787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ff5948f8b71'
down_revision = '69de1805334b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surname', sa.String(length=32), nullable=True))
        batch_op.create_unique_constraint('full name', ['name', 'surname'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author_model', schema=None) as batch_op:
        batch_op.drop_constraint('full name', type_='unique')
        batch_op.drop_column('surname')

    # ### end Alembic commands ###
